name: release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: extract
      - uses: shrink/actions-docker-extract@v1
        id: extract
        with:
          image: charesgregory/dlang-ldc-static-test-app:latest
          path: /home/test-app/test
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ steps.extract.outputs.destination }}
          generate_release_notes: true
          draft: true