name: release

on:
  workflow_run:
    workflows: ["build test app"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: extract
        uses: shrink/actions-docker-extract@v1
        id: extract
        with:
          image: charesgregory/dlang-ldc-static-test-app:latest
          path: /home/test-app/test

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.extract.outputs.destination }}/test
          generate_release_notes: true
          draft: true
          tag_name: ${{ steps.get_version.outputs.VERSION }}